---
abstract: 'Wrapper for Apache2 Action directive for running PSGI apps on shared hosting with FastCGI'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Apache-ActionWrapper
requires:
  ExtUtils::MakeMaker: 0
  Plack::Middleware: 0
  Test::More: 0
  base: 0
resources:
  repository: http://github.com/robinsmidsrod/Plack-App-Apache-ActionWrapper
version: 0.01
