---
abstract: 'Wrapper for Apache2 Action directive for running PSGI apps on shared hosting with FastCGI'
author:
  - 'Robin Smidsrød <robin@smidsrod.no>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-App-Apache-ActionWrapper
requires:
  File::Spec: 0
  Plack: 0.9021
  Plack::Component: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/robinsmidsrod/Plack-App-Apache-ActionWrapper.git
version: 0.31.0
